[project]
name = "reepy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Anantajit Subrahmanya", email = "anantajit@ucsb.edu" }
]
requires-python = ">=3.10"
dependencies = [
    "networkx>=3.4.2",
]

[project.scripts]
reepy = "reepy:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.4.0",
    "reepy",
]

[tool.uv.sources]
reepy = { workspace = true }
